# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founded_date',
        ),
    ]
